---
- name: Setup Nomad Cluster
  hosts: cluster
  become: true
  roles:
    - basic
    - docker
    - nomad

- name: Configure Nomad Servers
  hosts: leaders
  become: true
  gather_facts: false
  tasks:
    - name: Set up Nomad Server
      include_role:
        name: nomad
        tasks_from: config-nomad-server.yml

- name: Configure Nomad Clients
  hosts: workers
  become: true
  gather_facts: false
  tasks:
    - name: Set up Nomad Client
      include_role:
        name: nomad
        tasks_from: config-nomad-client.yml
