---
- name: Install and Start Docker on Ubuntu
  hosts: docker

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
