---
- name: Update all software on a host
  hosts: "{{ variable_host | default('null') }}"
  serial: '{{ variable_serial | default(1) }}'
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Get hostname
      ansible.builtin.shell:
        cmd: hostname
      register: hostname

    - ansible.builtin.debug:
        msg: 'Updating {{ hostname.stdout }}'

    - name: Setup Host
      ansible.builtin.shell:
        cmd: |
          # Configure sshd
          sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
          sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
          sed -i -e '/^PubkeyAuthentication/s/^.*$/PubkeyAuthentication yes/' /etc/ssh/sshd_config
          sed -i -e '$aAllowUsers {{ ansible_user }}' /etc/ssh/sshd_config
          # Configure Hostname
          sed -i '/preserve_hostname: false/c\preserve_hostname: true' /etc/cloud/cloud.cfg
          hostnamectl set-hostname {{ hostname.stdout }}.lan.mrugesh.net

    - name: Reboot the host
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 15
        post_reboot_delay: 15
        test_command: uptime

    - name: Check Hostname
      ansible.builtin.shell:
        cmd: hostname
      register: hostname_check

    - name: Display Hostname
      ansible.builtin.debug:
        msg: '{{ hostname_check.stdout }}'
