---
- name: Restart or Shutdown a machine
  hosts: "{{ variable_host | default('cluster') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Restart the host
      ansible.builtin.reboot:
        reboot_command: "shutdown -r now"
        test_command: "uptime"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 30
        msg: "Reboot initiated by Ansible"
      when: variable_shutdown is not defined

    - name: Shutdown the host
      community.general.shutdown:
        delay: 5
      when: variable_shutdown | default(false)
