---
- name: Update all software on a host
  hosts: "{{ variable_host | default('cluster') }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Autoclean old packages
      ansible.builtin.apt:
        autoclean: true
        force_apt_get: true

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: true
        force_apt_get: true

    - name: Restart the host
      ansible.builtin.reboot:
        reboot_command: "shutdown -r now"
        test_command: "uptime"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 30
        msg: "Reboot initiated by Ansible"
