---
- name: Update all software on a host
  hosts: "{{ variable_host | default('cluster') }}"
  become: true
  become_method: sudo

  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Autoclean old packages
      apt:
        autoclean: yes
        force_apt_get: yes

    - name: Autoremove unused packages
      apt:
        autoremove: yes
        force_apt_get: yes

    - name: restart the machine
      command: shutdown {{ var_reboot | default('-r') }} now
      async: 1
      poll: 0
      ignore_errors: true
